# Cập nhật URL ảnh QR mới
qr.image.url=https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFUOQwbC5EQNVtwuok2Ni1McPyt6VZyHSPLrfdinkqu10Zw-ILDqzFk7dZ&s=10

# Các thông tin tài khoản giữ nguyên hoặc điều chỉnh theo nhu cầu
bank.name=MoMo / EZEGO
account.holder=Ten Chu Tai Khoan
account.number=So Tai Khoan
transfer.content=Coc don hang #ORDER_ID - {ten_khach_hang}