hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://db.niytqxchqemlfzpugyyg.supabase.co:5432/postgres?sslmode=require
hibernate.connection.username=postgres
hibernate.connection.password=Lychanylen1
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
hibernate.connection.pool_size=5